version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx-irestore
    links:
    - irestore
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/irestore
    labels:
    - "traefik.http.routers.nginx-irestore-http.middlewares=redirect-to-https"
    - "traefik.http.routers.nginx-irestore-http.rule=Host(`api-irestore.mdhtcdn.net`)"
    - "traefik.http.routers.nginx-irestore.entrypoints=web,websecure"
    - "traefik.http.routers.nginx-irestore.rule=Host(`api-irestore.mdhtcdn.net`)"
    - "traefik.http.routers.nginx-irestore.tls=true"
    - "traefik.http.routers.nginx-irestore.tls.certresolver=leresolver"
    networks:
    - web
  irestore:
    container_name: irestore
    build: .
    networks:
      - web
networks:
  web:

