version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx-irestore
    links:
    - irestore
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/irestore
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.nginx-secretelement-http.middlewares=redirect-to-https"
    - "traefik.http.routers.nginx-secretelement-http.rule=Host(`dev.secretelement.uk`)"
    - "traefik.http.routers.nginx-secretelement.entrypoints=web,websecure"
    - "traefik.http.routers.nginx-secretelement.rule=Host(`dev.secretelement.uk`)"
    - "traefik.http.routers.nginx-secretelement.tls=true"
    - "traefik.http.routers.nginx-secretelement.tls.certresolver=leresolver"
    networks:
    - web
  irestore:
    container_name: irestore
    build: .
    networks:
      - web
networks:
  web:

